In [15]:
import numpy as np

In [16]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [17]:
arr[0]

2

In [18]:
cartela_bingo = np.array([[16, 10,  3, 15],
                            [14, 23, 17, 27],
                            [ 6, 19,  3,  1],
                            [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [19]:
cartela_bingo[:, 1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [20]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [21]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [22]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

## 1.1 Explorando Ecossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

**ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie**



*  Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
*  De qtd_especies selecione apenas as primeiras 3 quantidades e print
*  Print as 5 últimas quantidades de espécies
*  Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente






In [23]:
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [24]:
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [25]:
print(qtd_especies[:3])

[ 89 123  22]


In [26]:
print(qtd_especies[-5:])

[ 64  84 105 103 124]


In [27]:
tamanho_especies = especies[:, 3]
tamanho_especies.sort()
tamanho_especies

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

## Filtrando Arrays

In [28]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [29]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [30]:
cartela_bingo = np.array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

## 1.2 Ainda usando o Array de espécies marítimas.

*   Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

*   Usando fency index faça um array que contém apenas dados da espécie com ID 297
*   Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
*   Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"



In [31]:
especies

array([[747,  89,  33,   1],
       [623, 123,  32,   2],
       [501,  22,  49,   5],
       [116, 101,  42,   5],
       [297,  56,  69,   7],
       [613,  64,  27,  10],
       [295,  84,  29,  13],
       [692, 105,  72,  14],
       [229, 103,  35,  16],
       [374, 124,  70,  22]])

In [32]:
especies[:, 3] == 22


array([False, False, False, False, False, False, False, False, False,
        True])

In [33]:
maior_especie = especies[especies[:,3] == 22]

In [34]:
mask_297 = especies[:, 0] == 297

In [35]:
especies[mask_297]

array([[297,  56,  69,   7]])

In [36]:
np.where(especies[:, 1] == 105)

(array([7]),)

In [37]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  14]])

In [38]:
especies[:, 2] > 60

array([False, False, False, False,  True, False, False,  True, False,
        True])

In [39]:
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U21')

## 1.3 Ainda no conjunto 'especies'.

*   Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
*   Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]


In [40]:
novas_especies = np.array ([[204, 10, 40, 12],
                            [392, 11, 81, 11]])

In [41]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   1],
       [623, 123,  32,   2],
       [501,  22,  49,   5],
       [116, 101,  42,   5],
       [297,  56,  69,   7],
       [613,  64,  27,  10],
       [295,  84,  29,  13],
       [692, 105,  72,  14],
       [229, 103,  35,  16],
       [374, 124,  70,  22],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [42]:
visao = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1]).reshape((10,1))
visao

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [43]:
np.concatenate(((especies, visao)),axis=1)

array([[747,  89,  33,   1,   0],
       [623, 123,  32,   2,   1],
       [501,  22,  49,   5,   0],
       [116, 101,  42,   5,   0],
       [297,  56,  69,   7,   0],
       [613,  64,  27,  10,   0],
       [295,  84,  29,  13,   1],
       [692, 105,  72,  14,   0],
       [229, 103,  35,  16,   1],
       [374, 124,  70,  22,   1]])