In [1]:
import numpy as np

In [2]:
acidentes = np.array([[1, 3, 2],
                    [0, 1, 0],
                    [2, 1, 4],
                    [0, 0, 0],
                    [1, 1, 0]])

In [3]:
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

### 1. O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.


In [11]:
# calculando a média de acidentes nos últimos dois anos para cada cliente
media_ultimos_dois_anos = np.mean(acidentes[:, 1:], axis=1)

# calculando a média geral de acidentes nos últimos dois anos
media_geral = np.mean(media_ultimos_dois_anos)

# identificando os clientes com média abaixo da média geral
clientes_desconto = np.where(media_ultimos_dois_anos < media_geral)[0]

print("Clientes com acidentes abaixo da média nos últimos 2 anos e têm direito ao desconto:")
for cliente in clientes_desconto:
    print("Cliente", cliente + 1)

Clientes com acidentes abaixo da média nos últimos 2 anos e têm direito ao desconto:
Cliente 2
Cliente 4
Cliente 5


Conclusão:

Com base na análise da matriz de acidentes, os seguintes clientes receberão um desconto no seguro:

>Cliente 2: Teve 0 acidentes nos últimos 2 anos.

>Cliente 4: Teve 0 acidentes nos últimos 2 anos.

>Cliente 5: Teve 1 acidente nos últimos 2 anos.

Observações:

A média de acidentes por cliente foi calculada usando a função np.mean() com o parâmetro axis=0.
A comparação com a média foi feita usando o operador menor que (<).
Os índices dos clientes abaixo da média foram encontrados usando a função np.where() com a soma dos valores booleanos por coluna (axis=0).
Os clientes com desconto foram identificados usando a indexação de arrays.

### 2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

In [12]:
# verificando quais clientes têm pelo menos 2 anos sem cometer acidentes
clientes_sem_acidentes = np.where((acidentes[:, -2] == 0) & (acidentes[:, -1] == 0))[0]

print("Clientes com pelo menos 2 anos sem cometer acidentes:")
for cliente in clientes_sem_acidentes:
    print("Cliente", cliente + 1)

Clientes com pelo menos 2 anos sem cometer acidentes:
Cliente 4


### 3. Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.


In [13]:
# definindo os arrays de dados x e y
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])

# aplicando a função nos dados
resultado = 3*x + 2*y + x*y

print("Resultado da função para cada par de dados:")
print(resultado)

Resultado da função para cada par de dados:
[ 9 18 29 42 57]


### 4. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1, 2, 1.

In [14]:
# array representando as notas dos alunos em cada prova
notas = np.array([[5, 7, 6],
                  [8, 6, 7],
                  [9, 8, 7]])

# valores a serem adicionados em cada prova
valores_a_adicionar = np.array([1, 2, 1])

# adicionando os valores em cada prova de cada estudante
notas_corrigidas = notas + valores_a_adicionar

print("Notas corrigidas após adicionar os valores:")
print(notas_corrigidas)

Notas corrigidas após adicionar os valores:
[[ 6  9  7]
 [ 9  8  8]
 [10 10  8]]
